config/routes.rb
Rails.application.routes.draw do

  resources :credentials
  root 'home#index3'
  
  resources :webmasters
  resources :user_tickets
  resources :user_positions
  resources :transactions
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'
  resources :tickets
  get 'statement/index'

  get 'showcal/index'
  get 'home/index'
  get 'home/index2'
  get 'home/index3'
  get 'home/index6'
  get 'home/index6'
  get 'home/index7'
  get 'home/index8'
  get 'home/index9'
  
  resources :searches
  resources :partner_links
  resources :mstats
  resources :msponsors
  resources :mratings
  resources :mobjects
  resources :mdetails
  resources :mcategories
  resources :mcalendars
  resources :madvisors
  get 'listaccount/index'

  resources :favourits
  resources :emails
  resources :customers
  get 'customer_advisor/index'

  get 'customer_advisor/index2'

  resources :companies
  resources :appparams
  resources :appointments
  resources :appointment_documents
  resources :accounts
  root 'home#index3'

  devise_for :users, :controllers => {registrations: 'registrations'}
  
  resources :users
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mstat.rb
class Mstat < ActiveRecord::Base
    belongs_to :mobject
    belongs_to :owner, polymorphic: true
    #belongs_to :company
    #belongs_to :user
end

app/controllers/mstats_controller.rb
class MstatsController < ApplicationController
  before_action :set_mstat, only: [:show, :edit, :update, :destroy]

  # GET /mstats
  def index
    @mstats = Mstat.where("mobject_id=?", params[:mobject_id]).order(amount: :desc).page(params[:page]).per_page(10)
    @mstatanz = @mstats.count
  end

  # GET /mstats/1
  def show
  end

  # GET /mstats/new
  def new
    @mstat = Mstat.new
    @mstat.mobject_id = params[:mobject_id]
    @mstat.amount = Mobject.find(params[:mobject_id]).price
    @dontype = params[:dontype]
    if params[:dontype] == "User"
      @mstat.owner_id = current_user.id
      @mstat.owner_type = "User"
    else
      @mstat.owner_id = Company.where('active=? and user_id=?',true,current_user.id).first.id
      @mstat.owner_type = "Company"
    end
    @mstat.anonymous = false
  end

  # GET /mstats/1/edit
  def edit
    @mstat.status = "changed"
  end

  # POST /mstats
  def create
    @mstat = Mstat.new(mstat_params)
    if @mstat.save
      redirect_to mobject_path(:id => @mstat.mobject_id, :topic => "CF_Transaktionen"), notice: 'Mstat was successfully created.'
    else
      render :new
    end
  end

  # PUT /mstats/1
  def update
    if @mstat.update(mstat_params)
      redirect_to mobject_path(:id => @mstat.mobject_id, :topic => "CF_Transaktionen"), notice: 'Mstat was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /mstats/1
  def destroy
    @id = @mstat.mobject_id
    @mstat.destroy
    redirect_to mobject_path(:id => @id, :topic => "CF_Transaktionen"), notice: 'Mstat was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mstat
      @mstat = Mstat.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def mstat_params
      params.require(:mstat).permit(:status, :mobject_id, :owner_type, :owner_id, :user_id, :company_id, :amount, :anonymous)
    end

end

app/helpers/mstats_helper.rb
module MstatsHelper
end

app/views/mstats/_form.html.erb
  <%= form_for @mstat do |f| %>
     <div class="row">
        <div class="col-md-9">
            <div class="panel panel-heading header">
              <h1>
              <%= link_to mobject_path(:id => @mstat.mobject_id, :topic => "CF_Transaktionen") do %>
                <i class="btn btn-primary btn-lg glyphicon glyphicon-list"></i>
              <% end %>
              <% if @mstat.mobject.msubtype == "Spenden" %>
                SPENDER
              <% end %>
              <% if @mstat.mobject.msubtype == "Belohnungen" %>
                UNTERSTUETZER
              <% end %>
              <% if @mstat.mobject.msubtype == "Zinsen" %>
                KREDITGEBER
              <% end %>
              <% if @mstat.owner_type == "Company" %>
                <%= @mstat.owner.name %>
              <% end %>
              <% if @mstat.owner_type == "User" %>
                <%= @mstat.owner.name + " " + @mstat.owner.lastname %>
              <% end %>
              </h1>
            </div>
        </div>
     </div>

     <div class="row">
        <div class="col-md-9">
          <div class="panel-body">
            <% if @mstat.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@mstat.errors.count, "error") %> prohibited this workorder from being saved:</h2>
                <ul>
                  <% @mstat.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <% if @mstat.owner_type == "Company" %>
              <div class="form-group">
                <%= f.label "Institution" %><br/>
                  <%= f.collection_select :owner_id, Company.where('active=? and user_id=?',true,current_user.id), :id, :name, {}, class:"form-control" %>
              </div>
            <% else %>
              <%= f.hidden_field :owner_id, class:"form-control" %>
            <% end %>
            <%= f.hidden_field :mobject_id, class:"form-control" %>
            <%= f.hidden_field :owner_type, class:"form-control" %>
            <% if @mstat.mobject.msubtype == "Spenden" %>
              <div class="form-group">
                <%= f.label "Spendenbetrag" %><br/>
                <%= f.number_field :amount, class:"form-control"%>
              </div>
            <% end %>
            <% if @mstat.mobject.msubtype == "Belohnungen" %>
              <div class="form-group">
                <%= f.label "Unterstützungsbetrag" %><br/>
                <%= f.number_field :amount, :readonly => true, class:"form-control"%>
              </div>
            <% end %>
            <% if @mstat.mobject.msubtype == "Zinsen" %>
              <div class="form-group">
                <%= f.label "Kreditbetrag" %><br/>
                <%= f.number_field :amount, class:"form-control"%>
              </div>
            <% end %>
            <div class="form-group">
              <input type="checkbox" name="my-checkbox1" checked>
              <%= f.label "Anonym" %><br/>
            </div>
            <div class="actions">
              <%= f.submit "Speichern", class:"btn btn-primary btn-lg"%>
            </div>
                <%= f.check_box :anonymous, :id => "anonymous", class:"form-control hidden"%>
          </div>
        </div>
      </div>
  <% end %>

<script>
     $.fn.bootstrapSwitch.defaults.onColor = 'success';
     $("[name='my-checkbox1']").bootstrapSwitch('state',<%= @mstat.anonymous %>);
     $("[name='my-checkbox1']").on('switchChange.bootstrapSwitch', function () {
     $("#anonymous").prop('checked',$("[name='my-checkbox1']").bootstrapSwitch('state'));
     });
</script>

app/views/mstats/edit.html.erb
<%= render 'form' %>

app/views/mstats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mstats</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mstats.each do |mstat| %>
      <tr>
        <td><%= mstat.status %></td>
        <td><%= link_to 'Show', mstat %></td>
        <td><%= link_to 'Edit', edit_mstat_path(mstat) %></td>
        <td><%= link_to 'Destroy', mstat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mstat', new_mstat_path %>

app/views/mstats/new.html.erb
<%= render 'form' %>

app/views/mstats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @mstat.status %>
</p>

<%= link_to 'Edit', edit_mstat_path(@mstat) %> |
<%= link_to 'Back', mstats_path %>