config/routes.rb
Rails.application.routes.draw do

  resources :credentials
  root 'home#index3'
  
  resources :webmasters
  resources :user_tickets
  resources :user_positions
  resources :transactions
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'
  resources :tickets
  get 'statement/index'

  get 'showcal/index'
  get 'home/index'
  get 'home/index2'
  get 'home/index3'
  get 'home/index6'
  get 'home/index6'
  get 'home/index7'
  get 'home/index8'
  get 'home/index9'
  
  resources :searches
  resources :partner_links
  resources :mstats
  resources :msponsors
  resources :mratings
  resources :mobjects
  resources :mdetails
  resources :mcategories
  resources :mcalendars
  resources :madvisors
  get 'listaccount/index'

  resources :favourits
  resources :emails
  resources :customers
  get 'customer_advisor/index'

  get 'customer_advisor/index2'

  resources :companies
  resources :appparams
  resources :appointments
  resources :appointment_documents
  resources :accounts
  root 'home#index3'

  devise_for :users, :controllers => {registrations: 'registrations'}
  
  resources :users
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mcalendar.rb
class Mcalendar < ActiveRecord::Base
    belongs_to :mobject
    belongs_to :user
    #belongs_to :company
    
    validate :valid_dates?
    validates_inclusion_of :time_from, :in => 1..24
    validates_inclusion_of :time_to, :in => 1..24
    
  def self.search(mobject, cw, year)
    start_date = Date.commercial(year,cw,1)
    end_date = Date.commercial(year,cw,7)
    where('mobject_id=? and active=? and ((date_from>=? and date_from<=?) or (date_to>=? and date_to<=?) or (date_from<=? and date_to>=?))', mobject, true, start_date, end_date, start_date, end_date, start_date, end_date)
  end 

    def valid_dates?
      if date_from.to_date.is_a?(Date) and date_to.to_date.is_a?(Date)
        if date_from <= date_to
          if time_from < time_to
            return true
          end
        end
      end
      errors.add(:Date_from, "invalid date or time")
    end
end

app/controllers/mcalendars_controller.rb
class McalendarsController < ApplicationController
  before_action :set_mcalendar, only: [:show, :edit, :update, :destroy]

  # GET /mcalendars
  def index
    @mcalendars = Mcalendar.all
  end

  # GET /mcalendars/1
  def show
  end

  # GET /mcalendars/new
  def new
    @mcalendar = Mcalendar.new
    @mcalendar.mobject_id = params[:mobject_id]
    @mcalendar.user_id = current_user.id
    # @mcalendar.company_id = params[:company_id]
    @mcalendar.active = true
    @mcalendar.date_from = Date.today
    @mcalendar.date_to = Date.today
    @mcalendar.time_from = 8
    @mcalendar.time_to = 12
    @mcalendar.status = "new"
  end

  # GET /mcalendars/1/edit
  def edit
    @mcalendar.status = "changed"
  end

  # POST /mcalendars
  def create
    @mcalendar = Mcalendar.new(mcalendar_params)
    if @mcalendar.save
      redirect_to mobject_path(:id => @mcalendar.mobject_id, :topic => "Kalender", :year => session[:year], :cw => session[:cw]), notice: 'Calender entry was successfully created.'
    else
      render :new
    end
  end

  # PUT /mcalendars/1
  def update
    if @mcalendar.update(mcalendar_params)
      redirect_to mobject_path(:id => @mcalendar.mobject_id, :topic => "Kalender", :year => session[:year], :cw => session[:cw]), notice: 'Calender entry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /mcalendars/1
  def destroy
    @id = @mcalendar.mobject_id
    @mcalendar.destroy
      redirect_to mobject_path(:id => @id, :topic => "Kalender", :year => session[:year], :cw => session[:cw]), notice: 'Calender entry was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mcalendar
      @mcalendar = Mcalendar.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def mcalendar_params
      params.require(:mcalendar).permit(:mobject_id, :user_id, :company_id, :date_from, :date_to, :time_from, :time_to, :active, :status)
    end
    
end

app/helpers/mcalendars_helper.rb
module McalendarsHelper
def CalItem2(calendars, start)
    
    @mobject.time_to = 19 if !@mobject.time_to
    @mobject.time_from = 7 if !@mobject.time_from

    @anz_stunden = (@mobject.time_to - @mobject.time_from) + 1
    @anz_tage = 7
    @array = Array.new(@anz_stunden) {Array.new(@anz_tage)}

    for stunde in 0..@anz_stunden-1
        for tag in 0..@anz_tage-1
            @array[stunde][tag] = 0
        end
    end
    
    calendars.each do |c|
        
        von = DateTime.new(c.date_from.year,c.date_from.month,c.date_from.day,c.time_from)
        bis = DateTime.new(c.date_to.year,c.date_to.month,c.date_to.day,c.time_to)
        
        for stunde in 0..@anz_stunden-1
            for tag in 0..@anz_tage-1

                comp = DateTime.new((start+tag).year,(start+tag).month,(start+tag).day,c.mobject.time_from+stunde)
                
                if comp >= von and comp < bis
                    @array[stunde][tag] = c.id
                end

            end
        end
    end
    return @array
end

end

app/views/mcalendars/_form.html.erb
    <%= form_for @mcalendar do |f| %>

        <% if @mcalendar.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@mcalendar.errors.count, "error") %> prohibited this calender from being saved:</h2>
              <ul>
                  <% @mcalendar.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
              </ul>
            </div>
        <% end %>

        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading header">
                      <li_header>
                      <%= link_to mobject_path(:id => @mcalendar.mobject_id, :topic => "Kalender") do %>
                        <i class="btn btn-primary btn-lg glyphicon glyphicon-list"></i>
                      <% end %>
                      RESERVATION <%= @mcalendar.mobject.name %>
                      </li_header>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="panel-body">
                    <div class="form-group">
                      <%= f.label "Datum von" %><br/>
                      <%= f.text_field :date_from, class:"form-control"%>
                      <%= f.label "Uhrzeit von" %><br/>
                      <%= f.number_field :time_from, class:"form-control"%>
                    </div>
                    <div class="form-group">
                      <%= f.label "Datum_bis" %><br/>
                      <%= f.text_field :date_to, class:"form-control"%>
                      <%= f.label "Uhrzeit bis" %><br/>
                      <%= f.number_field :time_to, class:"form-control"%>
                    </div>
                   <%= f.hidden_field :mobject_id, class:"form-control" %>
                   <%= f.hidden_field :user_id, class:"form-control" %>
                   <%= f.hidden_field :company_id, class:"form-control" %>
                   <%= f.hidden_field :active, class:"form-control" %>
                    <div class="actions">
                       <%= f.submit "Speichern",  class:"btn btn-primary btn-lg"%>
                    </div>
                </div>
                
            </div>
        </div>
    <% end %>                

<script type="text/javascript">
  $(document).ready(function(){
    $('#mcalendar_date_from').datepicker({
        format: "yyyy-mm-dd",
        weekStart: 1,
        language: "en",
        daysOfWeekHighlighted: "0,6",
        todayBtn: true,
        todayHighlight: true,
        firstDay: 1}
    );
    $('#mcalendar_date_to').datepicker({
        format: "yyyy-mm-dd",
        weekStart: 1,
        language: "en",
        daysOfWeekHighlighted: "0,6",
        todayBtn: true,
        todayHighlight: true,
        firstDay: 1}
    );
  });
</script>

<script>
  document.addEventListener("turbolinks:load", function() {})
</script>

app/views/mcalendars/edit.html.erb
<%= render 'form' %>

app/views/mcalendars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mcalendars</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mcalendars.each do |mcalendar| %>
      <tr>
        <td><%= mcalendar.status %></td>
        <td><%= link_to 'Show', mcalendar %></td>
        <td><%= link_to 'Edit', edit_mcalendar_path(mcalendar) %></td>
        <td><%= link_to 'Destroy', mcalendar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mcalendar', new_mcalendar_path %>

app/views/mcalendars/new.html.erb
<%= render 'form' %>

app/views/mcalendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @mcalendar.status %>
</p>

<%= link_to 'Edit', edit_mcalendar_path(@mcalendar) %> |
<%= link_to 'Back', mcalendars_path %>