config/routes.rb
Rails.application.routes.draw do

  resources :credentials
  root 'home#index3'
  
  resources :webmasters
  resources :user_tickets
  resources :user_positions
  resources :transactions
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'
  resources :tickets
  get 'statement/index'

  get 'showcal/index'
  get 'home/index'
  get 'home/index2'
  get 'home/index3'
  get 'home/index6'
  get 'home/index6'
  get 'home/index7'
  get 'home/index8'
  get 'home/index9'
  
  resources :searches
  resources :partner_links
  resources :mstats
  resources :msponsors
  resources :mratings
  resources :mobjects
  resources :mdetails
  resources :mcategories
  resources :mcalendars
  resources :madvisors
  get 'listaccount/index'

  resources :favourits
  resources :emails
  resources :customers
  get 'customer_advisor/index'

  get 'customer_advisor/index2'

  resources :companies
  resources :appparams
  resources :appointments
  resources :appointment_documents
  resources :accounts
  root 'home#index3'

  devise_for :users, :controllers => {registrations: 'registrations'}
  
  resources :users
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_ticket.rb
class UserTicket < ActiveRecord::Base
    belongs_to :user
    belongs_to :ticket
end

app/controllers/user_tickets_controller.rb
class UserTicketsController < ApplicationController
  before_action :set_user_ticket, only: [:show, :edit, :update, :destroy]

  # GET /user_tickets
  def index
    @user_tickets = UserTicket.where('user_id=?',current_user.id)
  end

  # GET /user_tickets/1
  def show
  end

  # GET /user_tickets/new
  def new
    @user_ticket = UserTicket.new
    @user_ticket.user_id = params[:user_id]
    @user_ticket.ticket_id = params[:ticket_id]
    @user_ticket.status = "persönlich"
    @user_ticket.save
    redirect_to User.find(@user_ticket.user_id), notice: 'User ticket was successfully created.'    
  end

  # GET /user_tickets/1/edit
  def edit
  end

  # POST /user_tickets
  def create
    @user_ticket = UserTicket.new(user_ticket_params)

    if @user_ticket.save
      redirect_to @user_ticket, notice: 'User ticket was successfully created.'
    else
      render :new
    end
  end

  # PUT /user_tickets/1
  def update
    if @user_ticket.update(user_ticket_params)
      redirect_to @user_ticket, notice: 'User ticket was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /user_tickets/1
  def destroy
    @ticket_id = @user_ticket.ticket_id
    @user_ticket.destroy
    redirect_to ticketuserview_index_path :ticket_id => @ticket_id, notice: 'User ticket was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_ticket
      @user_ticket = UserTicket.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user_ticket).permit(:user_id, :ticket_id, :status)
    end

end

app/helpers/user_tickets_helper.rb
module UserTicketsHelper
end

app/views/user_tickets/_form.html.erb
<%= form_for(@user_ticket) do |f| %>
  <% if @user_ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_ticket.errors.count, "error") %> prohibited this user_ticket from being saved:</h2>

      <ul>
      <% @user_ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :ticket_id %><br>
    <%= f.number_field :ticket_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_tickets/edit.html.erb
<h1>Editing User Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_ticket %> |
<%= link_to 'Back', user_tickets_path %>

app/views/user_tickets/index.html.erb
  <div class="row">
     <div class="col-md-12">
       <div class="panel-heading header">
          <div class="li_header">
          meine Tickets
          <span class="badge"><%= @ticanz %></span>
          </div>
       </div>
     </div>
   </div>
   <br>
   
  <div class="panel-body">
  <% ticketcount = 0 %>
  <% @user_tickets.each do |ut| %>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <div class="thumbnail" align="center">
        <anzeigetext>
          <%= ut.ticket.ticket_category.name %><br>
					<%= ut.ticket.name %><br>
				</anzeigetext><br>
        <% if !ut.user.avatar_file_name %>
          <%= image_tag("user_a.png", :size => "50x50" , class:"img-rounded") %>
        <% else %>
          <%= image_tag ut.user.avatar(:small), class:"img-rounded"%>
        <% end %>
        <%= ut.user.name + " " + ut.user.lastname %><br>
        <ntext><br>
        <b>Veranstaltung</b><br>
        <%= link_to ut.ticket.sponsor.event do %>
          <%= carousel2(ut.ticket.sponsor.event.event_details, :medium) %><br>
        <% end %>
        <%= ut.ticket.sponsor.event.name %><br>
        <%= ut.ticket.sponsor.event.date_from.strftime("%d.%m.%Y") + " - " + ut.ticket.sponsor.event.date_to.strftime("%d.%m.%Y")  %><br>
        <br>
        <b>überreicht von</b><br>
        <% if !ut.ticket.sponsor.company.avatar_file_name %>
          <%= image_tag("user_a.png", :size => "50x50" , class:"img-rounded") %>
        <% else %>
          <%= image_tag ut.ticket.sponsor.company.avatar(:small), class:"img-rounded"%>
        <% end %>
        <%= ut.ticket.sponsor.company.name %>
        </ntext>
        <div class="caption">
            <ntext>
  				  <%= ut.ticket.description %>
            </ntext>
  			</div>
        <ntext>
  		  <%= ut.ticket.created_at.strftime("%d.%b.%Y %H:%M Uhr") %>
  		  <% if ut.ticket.created_at.to_date == Date.today %>
  		    Heute
  		  <% end %>
  		  <% if (Date.today - ut.ticket.created_at.to_date) == 1 %>
  		    Gestern
  		  <% end %>
  		  <% if Date.today - ut.ticket.created_at.to_date > 1 %>
          <% anz = (Date.today.to_date - ut.ticket.created_at.to_date).to_i %>
          Vor <%= anz %> Tagen
  		  <% end %>
        </ntext>    		  
        </p>
  			<p>
  			<% case ut.status %>
  			  <% when "überreicht" %>
            <%= link_to edit_user_ticket_path(ut) do %>
              <i class="btn btn-primary btn btn-lg glyphicon glyphicon-shopping-cart"> Ticket aktivieren</i>
            <% end %>
  			  <% when "aktiviert" %>
            <%= link_to edit_user_ticket_path(ut) do %>
              <i class="btn btn-primary btn btn-lg glyphicon glyphicon-shopping-cart"> Ticket einlösen</i>
            <% end %>
        <% end %>
  		</div>
		</div>
  <% end %>
  </div>

app/views/user_tickets/new.html.erb
<h1>New User Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tickets_path %>

app/views/user_tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_ticket.user_id %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= @user_ticket.ticket_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user_ticket.status %>
</p>

<%= link_to 'Edit', edit_user_ticket_path(@user_ticket) %> |
<%= link_to 'Back', user_tickets_path %>